### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by mmmtsuko** [mmmtsuko/protospace-36545#4]
ご確認をよろしくお願いいたします。

#URL
https://protospace-36545.herokuapp.com/users/sign_in

**Comment by miyu-yamamoto** [comment]
@mmmtsuko さん、お待たせいたしました。
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
